import initialContent from '../../../content/site.json';
export type Ingredient = {
  id: string;
  name: string;
  image: string;
  description: string;
  coreFlavor: string;
};
export type Product = {
  id: string;
  slug: string;
  name: string;
  category: string;
  weight: string;
  flavor: string;
  description: string;
  tagline?: string;
  packaging?: string;
  packageContents?: string[];
  ingredients?: string;
  ingredientImage?: string;
  ingredientIds?: string[];
  allergens?: string;
  storage?: string;
  image: string;
  price: number | null;
  featured: boolean;
};
export type Site = typeof initialContent.site;
export type Content = { site: Site; products: Product[]; ingredients?: Ingredient[] };
export const seed: Content = initialContent;
