"""Build portable home fallback faces from the existing licensed brand fonts.

Requires fonttools[woff]. Run from any directory with Python 3.12+.
The result is checked in; no Python/font tooling is needed by the application.
"""

import base64
from io import BytesIO
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

root = Path(__file__).resolve().parents[1]
source = root / "frontend/public/brand/fonts"
destination = root / "frontend/src/pages/home-critical-fonts.css"

# ASCII/Latin-1 plus every Vietnamese letter and punctuation used by editable copy.
# Keep complete character coverage rather than deriving glyphs from today's hero text.
unicodes = set(range(0x20, 0x100)) | set(range(0x1EA0, 0x1EFA)) | {
    0x0102, 0x0103, 0x0110, 0x0111, 0x0128, 0x0129,
    0x0168, 0x0169, 0x01A0, 0x01A1, 0x01AF, 0x01B0,
    0x0300, 0x0301, 0x0302, 0x0303, 0x0306, 0x0309, 0x031B, 0x0323,
    0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2026,
    0x20AB, 0x20AC,
}
faces = [
    ("noto-serif-regular.woff2", "Home Serif Fallback", "normal", "400"),
    ("noto-serif-italic.woff2", "Home Serif Fallback", "italic", "400"),
    ("archivo-expanded-regular.woff2", "Home UI Fallback", "normal", "100 900"),
]
rules = [
    "/* Generated by scripts/build-home-fallback-fonts.py. Brand glyph metrics remain unchanged. */"
]
for filename, family, style, weight in faces:
    font = TTFont(source / filename, recalcTimestamp=False)
    options = subset.Options()
    options.layout_features = ["ccmp", "mark", "mkmk", "kern", "liga"]
    options.hinting = False
    options.flavor = "woff2"
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=unicodes)
    subsetter.subset(font)
    output = BytesIO()
    font.save(output, reorderTables=True)
    data = output.getvalue()
    encoded = base64.b64encode(data).decode("ascii")
    rules.append(
        "@font-face {\n"
        f"  font-family: '{family}';\n"
        f"  src: url('data:font/woff2;base64,{encoded}') format('woff2');\n"
        f"  font-style: {style};\n"
        f"  font-weight: {weight};\n"
        "}\n"
    )
    print(f"{filename}: {len(data)} bytes")
destination.write_text("\n".join(rules), encoding="utf-8")
